package connection.init.InitPieces;
import java.sql.*;

public class InitPion {

  static final String CONN_URL = "jdbc:oracle:thin:@ensioracle1.imag.fr:1521:ensioracle1";
  static final String USER = "dhouibd"; // A remplacer pour votre compte
  static final String PASSWD = "dhouibd";

  // static final String STMTDrop = "Drop TABLE Pion";
  // static final String STMTCreate = "CREATE TABLE Pion(idPion INTEGER NOT NULL ,typePion varchar(20) NOT NULL CHECK(typePion in('roi','reine','tour','fou','Pion','pion')),posX character check(posX in ('A','B','C','D','E','F','G','H')),posY integer check(posY<9),oldX character check(oldX in ('A','B','C','D','E','F','G','H')),oldY integer check(oldY<9),couleur	character varying(5) check(couleur in('blanc','noir')), numRencontre integer not null, nomTour varchar(20) not null, PRIMARY KEY(idPion), foreign key(numRencontre,nomTour) REFERENCES Rencontre(numRencontre,nomTour))";


  // Finale
  static final String STMT1 = "Insert into Pion Values('1','A','2','A','2','blanc','1', 'finale')";
  static final String STMT2 = "Insert into Pion Values('2','H','2','H','2','blanc','1', 'finale')";
  static final String STMT3 = "Insert into Pion Values('3','B','2','B','2','blanc','1', 'finale')";
  static final String STMT4 = "Insert into Pion Values('4','G','2','G','2','blanc','1', 'finale')";
  static final String STMT5 = "Insert into Pion Values('5','C','2','C','2','blanc','1', 'finale')";
  static final String STMT6 = "Insert into Pion Values('6','F','2','F','2','blanc','1', 'finale')";
  static final String STMT7 = "Insert into Pion Values('7','D','2','D','2','blanc','1', 'finale')";
  static final String STMT8 = "Insert into Pion Values('8','E','2','E','2','blanc','1', 'finale')";
  static final String STMT9 = "Insert into Pion Values('9','A','7','A','7','noir','1', 'finale')";
  static final String STMT10 = "Insert into Pion Values('10','H','7','H','7','noir','1', 'finale')";
  static final String STMT11 = "Insert into Pion Values('11','B','7','B','7','noir','1', 'finale')";
  static final String STMT12 = "Insert into Pion Values('12','G','7','G','7','noir','1', 'finale')";
  static final String STMT13 = "Insert into Pion Values('13','C','7','C','7','noir','1', 'finale')";
  static final String STMT14 = "Insert into Pion Values('14','F','7','F','7','noir','1', 'finale')";
  static final String STMT15 = "Insert into Pion Values('15','D','7','D','7','noir','1', 'finale')";
  static final String STMT16 = "Insert into Pion Values('16','E','7','E','7','noir','1', 'finale')";


  // Demies finale
  static final String STMT17 = "Insert into Pion Values('17','A','2','A','2','blanc','1', 'demiFinale')";
  static final String STMT18 = "Insert into Pion Values('18','H','2','H','2','blanc','1', 'demiFinale')";
  static final String STMT19 = "Insert into Pion Values('19','B','2','B','2','blanc','1', 'demiFinale')";
  static final String STMT20 = "Insert into Pion Values('20','G','2','G','2','blanc','1', 'demiFinale')";
  static final String STMT21 = "Insert into Pion Values('21','C','2','C','2','blanc','1', 'demiFinale')";
  static final String STMT22 = "Insert into Pion Values('22','F','2','F','2','blanc','1', 'demiFinale')";
  static final String STMT23 = "Insert into Pion Values('23','D','2','D','2','blanc','1', 'demiFinale')";
  static final String STMT24 = "Insert into Pion Values('24','E','2','E','2','blanc','1', 'demiFinale')";
  static final String STMT25 = "Insert into Pion Values('25','A','7','A','7','noir','1', 'demiFinale')";
  static final String STMT26 = "Insert into Pion Values('26','H','7','H','7','noir','1', 'demiFinale')";
  static final String STMT27 = "Insert into Pion Values('27','B','7','B','7','noir','1', 'demiFinale')";
  static final String STMT28 = "Insert into Pion Values('28','G','7','G','7','noir','1', 'demiFinale')";
  static final String STMT29 = "Insert into Pion Values('29','C','7','C','7','noir','1', 'demiFinale')";
  static final String STMT30 = "Insert into Pion Values('30','F','7','F','7','noir','1', 'demiFinale')";
  static final String STMT31 = "Insert into Pion Values('31','D','7','D','7','noir','1', 'demiFinale')";
  static final String STMT32 = "Insert into Pion Values('32','E','7','E','7','noir','1', 'demiFinale')";
  static final String STMT33 = "Insert into Pion Values('33','A','2','A','2','blanc','2', 'demiFinale')";
  static final String STMT34 = "Insert into Pion Values('34','H','2','H','2','blanc','2', 'demiFinale')";
  static final String STMT35 = "Insert into Pion Values('35','B','2','B','2','blanc','2', 'demiFinale')";
  static final String STMT36 = "Insert into Pion Values('36','G','2','G','2','blanc','2', 'demiFinale')";
  static final String STMT37 = "Insert into Pion Values('37','C','2','C','2','blanc','2', 'demiFinale')";
  static final String STMT38 = "Insert into Pion Values('38','F','2','F','2','blanc','2', 'demiFinale')";
  static final String STMT39 = "Insert into Pion Values('39','D','2','D','2','blanc','2', 'demiFinale')";
  static final String STMT40 = "Insert into Pion Values('40','E','2','E','2','blanc','2', 'demiFinale')";
  static final String STMT41 = "Insert into Pion Values('41','A','7','A','7','noir','2', 'demiFinale')";
  static final String STMT42 = "Insert into Pion Values('42','H','7','H','7','noir','2', 'demiFinale')";
  static final String STMT43 = "Insert into Pion Values('43','B','7','B','7','noir','2', 'demiFinale')";
  static final String STMT44 = "Insert into Pion Values('44','G','7','G','7','noir','2', 'demiFinale')";
  static final String STMT45 = "Insert into Pion Values('45','C','7','C','7','noir','2', 'demiFinale')";
  static final String STMT46 = "Insert into Pion Values('46','F','7','F','7','noir','2', 'demiFinale')";
  static final String STMT47 = "Insert into Pion Values('47','D','7','D','7','noir','2', 'demiFinale')";
  static final String STMT48 = "Insert into Pion Values('48','E','7','E','7','noir','2', 'demiFinale')";

  // Quarts de finale
  static final String STMT49 = "Insert into Pion Values('49','A','2','A','2','blanc','1', 'quartFinale')";
  static final String STMT50 = "Insert into Pion Values('50','H','2','H','2','blanc','1', 'quartFinale')";
  static final String STMT51 = "Insert into Pion Values('51','B','2','B','2','blanc','1', 'quartFinale')";
  static final String STMT52 = "Insert into Pion Values('52','G','2','G','2','blanc','1', 'quartFinale')";
  static final String STMT53 = "Insert into Pion Values('53','C','2','C','2','blanc','1', 'quartFinale')";
  static final String STMT54 = "Insert into Pion Values('54','F','2','F','2','blanc','1', 'quartFinale')";
  static final String STMT55 = "Insert into Pion Values('55','D','2','D','2','blanc','1', 'quartFinale')";
  static final String STMT56 = "Insert into Pion Values('56','E','2','E','2','blanc','1', 'quartFinale')";
  static final String STMT57 = "Insert into Pion Values('57','A','7','A','7','noir','1', 'quartFinale')";
  static final String STMT58 = "Insert into Pion Values('58','H','7','H','7','noir','1', 'quartFinale')";
  static final String STMT59 = "Insert into Pion Values('59','B','7','B','7','noir','1', 'quartFinale')";
  static final String STMT60 = "Insert into Pion Values('60','G','7','G','7','noir','1', 'quartFinale')";
  static final String STMT61 = "Insert into Pion Values('61','C','7','C','7','noir','1', 'quartFinale')";
  static final String STMT62 = "Insert into Pion Values('62','F','7','F','7','noir','1', 'quartFinale')";
  static final String STMT63 = "Insert into Pion Values('63','D','7','D','7','noir','1', 'quartFinale')";
  static final String STMT64 = "Insert into Pion Values('64','E','7','E','7','noir','1', 'quartFinale')";
  static final String STMT65 = "Insert into Pion Values('65','A','2','A','2','blanc','2', 'quartFinale')";
  static final String STMT66 = "Insert into Pion Values('66','H','2','H','2','blanc','2', 'quartFinale')";
  static final String STMT67 = "Insert into Pion Values('67','B','2','B','2','blanc','2', 'quartFinale')";
  static final String STMT68 = "Insert into Pion Values('68','G','2','G','2','blanc','2', 'quartFinale')";
  static final String STMT69 = "Insert into Pion Values('69','C','2','C','2','blanc','2', 'quartFinale')";
  static final String STMT70 = "Insert into Pion Values('70','F','2','F','2','blanc','2', 'quartFinale')";
  static final String STMT71 = "Insert into Pion Values('71','D','2','D','2','blanc','2', 'quartFinale')";
  static final String STMT72 = "Insert into Pion Values('72','E','2','E','2','blanc','2', 'quartFinale')";
  static final String STMT73 = "Insert into Pion Values('73','A','7','A','7','noir','2', 'quartFinale')";
  static final String STMT74 = "Insert into Pion Values('74','H','7','H','7','noir','2', 'quartFinale')";
  static final String STMT75 = "Insert into Pion Values('75','B','7','B','7','noir','2', 'quartFinale')";
  static final String STMT76 = "Insert into Pion Values('76','G','7','G','7','noir','2', 'quartFinale')";
  static final String STMT77 = "Insert into Pion Values('77','C','7','C','7','noir','2', 'quartFinale')";
  static final String STMT78 = "Insert into Pion Values('78','F','7','F','7','noir','2', 'quartFinale')";
  static final String STMT79 = "Insert into Pion Values('79','D','7','D','7','noir','2', 'quartFinale')";
  static final String STMT80 = "Insert into Pion Values('80','E','7','E','7','noir','2', 'quartFinale')";
  static final String STMT81 = "Insert into Pion Values('81','A','2','A','2','blanc','3', 'quartFinale')";
  static final String STMT82 = "Insert into Pion Values('82','H','2','H','2','blanc','3', 'quartFinale')";
  static final String STMT83 = "Insert into Pion Values('83','B','2','B','2','blanc','3', 'quartFinale')";
  static final String STMT84 = "Insert into Pion Values('84','G','2','G','2','blanc','3', 'quartFinale')";
  static final String STMT85 = "Insert into Pion Values('85','C','2','C','2','blanc','3', 'quartFinale')";
  static final String STMT86 = "Insert into Pion Values('86','F','2','F','2','blanc','3', 'quartFinale')";
  static final String STMT87 = "Insert into Pion Values('87','D','2','D','2','blanc','3', 'quartFinale')";
  static final String STMT88 = "Insert into Pion Values('88','E','2','E','2','blanc','3', 'quartFinale')";
  static final String STMT89 = "Insert into Pion Values('89','A','7','A','7','noir','3', 'quartFinale')";
  static final String STMT90 = "Insert into Pion Values('90','H','7','H','7','noir','3', 'quartFinale')";
  static final String STMT91 = "Insert into Pion Values('91','B','7','B','7','noir','3', 'quartFinale')";
  static final String STMT92 = "Insert into Pion Values('92','G','7','G','7','noir','3', 'quartFinale')";
  static final String STMT93 = "Insert into Pion Values('93','C','7','C','7','noir','3', 'quartFinale')";
  static final String STMT94 = "Insert into Pion Values('94','F','7','F','7','noir','3', 'quartFinale')";
  static final String STMT95 = "Insert into Pion Values('95','D','7','D','7','noir','3', 'quartFinale')";
  static final String STMT96 = "Insert into Pion Values('96','E','7','E','7','noir','3', 'quartFinale')";
  static final String STMT97 = "Insert into Pion Values('97','A','2','A','2','blanc','4', 'quartFinale')";
  static final String STMT98 = "Insert into Pion Values('98','H','2','H','2','blanc','4', 'quartFinale')";
  static final String STMT99 = "Insert into Pion Values('99','B','2','B','2','blanc','4', 'quartFinale')";
  static final String STMT100 = "Insert into Pion Values('100','G','2','G','2','blanc','4', 'quartFinale')";
  static final String STMT101 = "Insert into Pion Values('101','C','2','C','2','blanc','4', 'quartFinale')";
  static final String STMT102 = "Insert into Pion Values('102','F','2','F','2','blanc','4', 'quartFinale')";
  static final String STMT103 = "Insert into Pion Values('103','D','2','D','2','blanc','4', 'quartFinale')";
  static final String STMT104 = "Insert into Pion Values('104','E','2','E','2','blanc','4', 'quartFinale')";
  static final String STMT105 = "Insert into Pion Values('105','A','7','A','7','noir','4', 'quartFinale')";
  static final String STMT106 = "Insert into Pion Values('106','H','7','H','7','noir','4', 'quartFinale')";
  static final String STMT107 = "Insert into Pion Values('107','B','7','B','7','noir','4', 'quartFinale')";
  static final String STMT108 = "Insert into Pion Values('108','G','7','G','7','noir','4', 'quartFinale')";
  static final String STMT109 = "Insert into Pion Values('109','C','7','C','7','noir','4', 'quartFinale')";
  static final String STMT110 = "Insert into Pion Values('110','F','7','F','7','noir','4', 'quartFinale')";
  static final String STMT111 = "Insert into Pion Values('111','D','7','D','7','noir','4', 'quartFinale')";
  static final String STMT112 = "Insert into Pion Values('112','E','7','E','7','noir','4', 'quartFinale')";

  // Qualifications
  static final String STMTP1B = "Insert into Pion Values('?','A','2','A','2','blanc','?', 'qualifications')";
  static final String STMTP2B = "Insert into Pion Values('?','H','2','H','2','blanc','?', 'qualifications')";
  static final String STMTP3B = "Insert into Pion Values('?','B','2','B','2','blanc','?', 'qualifications')";
  static final String STMTP4B = "Insert into Pion Values('?','G','2','G','2','blanc','?', 'qualifications')";
  static final String STMTP5B = "Insert into Pion Values('?','C','2','C','2','blanc','?', 'qualifications')";
  static final String STMTP6B = "Insert into Pion Values('?','F','2','F','2','blanc','?', 'qualifications')";
  static final String STMTP7B = "Insert into Pion Values('?','D','2','D','2','blanc','?', 'qualifications')";
  static final String STMTP8B = "Insert into Pion Values('?','E','2','E','2','blanc','?', 'qualifications')";
  static final String STMTP1N = "Insert into Pion Values('?','A','7','A','7','noir','?', 'qualifications')";
  static final String STMTP2N = "Insert into Pion Values('?','H','7','H','7','noir','?', 'qualifications')";
  static final String STMTP3N = "Insert into Pion Values('?','B','7','B','7','noir','?', 'qualifications')";
  static final String STMTP4N = "Insert into Pion Values('?','G','7','G','7','noir','?', 'qualifications')";
  static final String STMTP5N = "Insert into Pion Values('?','C','7','C','7','noir','?', 'qualifications')";
  static final String STMTP6N = "Insert into Pion Values('?','F','7','F','7','noir','?', 'qualifications')";
  static final String STMTP7N = "Insert into Pion Values('?','D','7','D','7','noir','?', 'qualifications')";
  static final String STMTP8N = "Insert into Pion Values('?','E','7','E','7','noir','?', 'qualifications')";

  public InitPion(int nbRencontresQualif) {

    try {
      // Enregistrement du driver
        System.out.print("Loading Oracle driver... ");
        DriverManager.registerDriver(new oracle.jdbc.driver.OracleDriver());
        System.out.println("loaded");
        // Etablissement de la connection
        System.out.print("Connecting to the database... ");
        Connection conn = DriverManager.getConnection(CONN_URL, USER, PASSWD);
        System.out.println("connected");
        conn.setAutoCommit(false);
        // Creation de la requete

        Statement stmt = conn.createStatement();
        // ResultSet rsetDrop = stmt.executeQuery(STMTDrop);
        // ResultSet rsetCreate = stmt.executeQuery(STMTCreate);

        ResultSet rset1 = stmt.executeQuery(STMT1);
        ResultSet rset2 = stmt.executeQuery(STMT2);
        ResultSet rset3 = stmt.executeQuery(STMT3);
        ResultSet rset4 = stmt.executeQuery(STMT4);
        ResultSet rset5 = stmt.executeQuery(STMT5);
        ResultSet rset6 = stmt.executeQuery(STMT6);
        ResultSet rset7 = stmt.executeQuery(STMT7);
        ResultSet rset8 = stmt.executeQuery(STMT8);
        ResultSet rset9 = stmt.executeQuery(STMT9);
        ResultSet rset10 = stmt.executeQuery(STMT10);
        ResultSet rset11 = stmt.executeQuery(STMT11);
        ResultSet rset12 = stmt.executeQuery(STMT12);
        ResultSet rset13 = stmt.executeQuery(STMT13);
        ResultSet rset14 = stmt.executeQuery(STMT14);
        ResultSet rset15 = stmt.executeQuery(STMT15);
        ResultSet rset16 = stmt.executeQuery(STMT16);
        ResultSet rset17 = stmt.executeQuery(STMT17);
        ResultSet rset18 = stmt.executeQuery(STMT18);
        ResultSet rset19 = stmt.executeQuery(STMT19);
        ResultSet rset20 = stmt.executeQuery(STMT20);
        ResultSet rset21 = stmt.executeQuery(STMT21);
        ResultSet rset22 = stmt.executeQuery(STMT22);
        ResultSet rset23 = stmt.executeQuery(STMT23);
        ResultSet rset24 = stmt.executeQuery(STMT24);
        ResultSet rset25 = stmt.executeQuery(STMT25);
        ResultSet rset26 = stmt.executeQuery(STMT26);
        ResultSet rset27 = stmt.executeQuery(STMT27);
        ResultSet rset28 = stmt.executeQuery(STMT28);
        ResultSet rset29 = stmt.executeQuery(STMT29);
        ResultSet rset30 = stmt.executeQuery(STMT30);
        ResultSet rset31 = stmt.executeQuery(STMT31);
        ResultSet rset32 = stmt.executeQuery(STMT32);
        ResultSet rset33 = stmt.executeQuery(STMT33);
        ResultSet rset34 = stmt.executeQuery(STMT34);
        ResultSet rset35 = stmt.executeQuery(STMT35);
        ResultSet rset36 = stmt.executeQuery(STMT36);
        ResultSet rset37 = stmt.executeQuery(STMT37);
        ResultSet rset38 = stmt.executeQuery(STMT38);
        ResultSet rset39 = stmt.executeQuery(STMT39);
        ResultSet rset40 = stmt.executeQuery(STMT40);
        ResultSet rset41 = stmt.executeQuery(STMT41);
        ResultSet rset42 = stmt.executeQuery(STMT42);
        ResultSet rset43 = stmt.executeQuery(STMT43);
        ResultSet rset44 = stmt.executeQuery(STMT44);
        ResultSet rset45 = stmt.executeQuery(STMT45);
        ResultSet rset46 = stmt.executeQuery(STMT46);
        ResultSet rset47 = stmt.executeQuery(STMT47);
        ResultSet rset48 = stmt.executeQuery(STMT48);
        ResultSet rset49 = stmt.executeQuery(STMT49);
        ResultSet rset50 = stmt.executeQuery(STMT50);
        ResultSet rset51 = stmt.executeQuery(STMT51);
        ResultSet rset52 = stmt.executeQuery(STMT52);
        ResultSet rset53 = stmt.executeQuery(STMT53);
        ResultSet rset54 = stmt.executeQuery(STMT54);
        ResultSet rset55 = stmt.executeQuery(STMT55);
        ResultSet rset56 = stmt.executeQuery(STMT56);
        ResultSet rset57 = stmt.executeQuery(STMT57);
        ResultSet rset58 = stmt.executeQuery(STMT58);
        ResultSet rset59 = stmt.executeQuery(STMT59);
        ResultSet rset60 = stmt.executeQuery(STMT60);
        ResultSet rset61 = stmt.executeQuery(STMT61);
        ResultSet rset62 = stmt.executeQuery(STMT62);
        ResultSet rset63 = stmt.executeQuery(STMT63);
        ResultSet rset64 = stmt.executeQuery(STMT64);
        ResultSet rset65 = stmt.executeQuery(STMT65);
        ResultSet rset66 = stmt.executeQuery(STMT66);
        ResultSet rset67 = stmt.executeQuery(STMT67);
        ResultSet rset68 = stmt.executeQuery(STMT68);
        ResultSet rset69 = stmt.executeQuery(STMT69);
        ResultSet rset70 = stmt.executeQuery(STMT70);
        ResultSet rset71 = stmt.executeQuery(STMT71);
        ResultSet rset72 = stmt.executeQuery(STMT72);
        ResultSet rset73 = stmt.executeQuery(STMT73);
        ResultSet rset74 = stmt.executeQuery(STMT74);
        ResultSet rset75 = stmt.executeQuery(STMT75);
        ResultSet rset76 = stmt.executeQuery(STMT76);
        ResultSet rset77 = stmt.executeQuery(STMT77);
        ResultSet rset78 = stmt.executeQuery(STMT78);
        ResultSet rset79 = stmt.executeQuery(STMT79);
        ResultSet rset80 = stmt.executeQuery(STMT80);
        ResultSet rset81 = stmt.executeQuery(STMT81);
        ResultSet rset82 = stmt.executeQuery(STMT82);
        ResultSet rset83 = stmt.executeQuery(STMT83);
        ResultSet rset84 = stmt.executeQuery(STMT84);
        ResultSet rset85 = stmt.executeQuery(STMT85);
        ResultSet rset86 = stmt.executeQuery(STMT86);
        ResultSet rset87 = stmt.executeQuery(STMT87);
        ResultSet rset88 = stmt.executeQuery(STMT88);
        ResultSet rset89 = stmt.executeQuery(STMT89);
        ResultSet rset90 = stmt.executeQuery(STMT90);
        ResultSet rset91 = stmt.executeQuery(STMT91);
        ResultSet rset92 = stmt.executeQuery(STMT92);
        ResultSet rset93 = stmt.executeQuery(STMT93);
        ResultSet rset94 = stmt.executeQuery(STMT94);
        ResultSet rset95 = stmt.executeQuery(STMT95);
        ResultSet rset96 = stmt.executeQuery(STMT96);
        ResultSet rset97 = stmt.executeQuery(STMT97);
        ResultSet rset98 = stmt.executeQuery(STMT98);
        ResultSet rset99 = stmt.executeQuery(STMT99);
        ResultSet rset100 = stmt.executeQuery(STMT100);
        ResultSet rset101 = stmt.executeQuery(STMT101);
        ResultSet rset102 = stmt.executeQuery(STMT102);
        ResultSet rset103 = stmt.executeQuery(STMT103);
        ResultSet rset104 = stmt.executeQuery(STMT104);
        ResultSet rset105 = stmt.executeQuery(STMT105);
        ResultSet rset106 = stmt.executeQuery(STMT106);
        ResultSet rset107 = stmt.executeQuery(STMT107);
        ResultSet rset108 = stmt.executeQuery(STMT108);
        ResultSet rset109 = stmt.executeQuery(STMT109);
        ResultSet rset110 = stmt.executeQuery(STMT110);
        ResultSet rset111 = stmt.executeQuery(STMT111);
        ResultSet rset112 = stmt.executeQuery(STMT112);



        int i=1;
        int numRencontre = 1;
        for(i=113; i<=113+nbRencontresQualif*16; i+=16) {
          PreparedStatement statementP1B = conn.prepareStatement(STMTP1B);
          statementP1B.setObject(1,i);
          statementP1B.setObject(2,numRencontre);
          statementP1B.executeUpdate();
          PreparedStatement statementP2B = conn.prepareStatement(STMTP2B);
          statementP2B.setObject(1,i);
          statementP2B.setObject(2,numRencontre);
          statementP2B.executeUpdate();
          PreparedStatement statementP3B = conn.prepareStatement(STMTP3B);
          statementP3B.setObject(1,i);
          statementP3B.setObject(2,numRencontre);
          statementP3B.executeUpdate();
          PreparedStatement statementP4B = conn.prepareStatement(STMTP4B);
          statementP4B.setObject(1,i);
          statementP4B.setObject(2,numRencontre);
          statementP4B.executeUpdate();
          PreparedStatement statementP5B = conn.prepareStatement(STMTP5B);
          statementP5B.setObject(1,i);
          statementP5B.setObject(2,numRencontre);
          statementP5B.executeUpdate();
          PreparedStatement statementP6B = conn.prepareStatement(STMTP6B);
          statementP6B.setObject(1,i);
          statementP6B.setObject(2,numRencontre);
          statementP6B.executeUpdate();
          PreparedStatement statementP7B = conn.prepareStatement(STMTP7B);
          statementP7B.setObject(1,i);
          statementP7B.setObject(2,numRencontre);
          statementP7B.executeUpdate();
          PreparedStatement statementP8B = conn.prepareStatement(STMTP8B);
          statementP8B.setObject(1,i);
          statementP8B.setObject(2,numRencontre);
          statementP8B.executeUpdate();
          PreparedStatement statementP1N = conn.prepareStatement(STMTP1N);
          statementP1N.setObject(1,i);
          statementP1N.setObject(2,numRencontre);
          statementP1N.executeUpdate();
          PreparedStatement statementP2N = conn.prepareStatement(STMTP2N);
          statementP2N.setObject(1,i);
          statementP2N.setObject(2,numRencontre);
          statementP2N.executeUpdate();
          PreparedStatement statementP3N = conn.prepareStatement(STMTP3N);
          statementP3N.setObject(1,i);
          statementP3N.setObject(2,numRencontre);
          statementP3N.executeUpdate();
          PreparedStatement statementP4N = conn.prepareStatement(STMTP4N);
          statementP4N.setObject(1,i);
          statementP4N.setObject(2,numRencontre);
          statementP4N.executeUpdate();
          PreparedStatement statementP5N = conn.prepareStatement(STMTP5N);
          statementP5N.setObject(1,i);
          statementP5N.setObject(2,numRencontre);
          statementP5N.executeUpdate();
          PreparedStatement statementP6N = conn.prepareStatement(STMTP6N);
          statementP6N.setObject(1,i);
          statementP6N.setObject(2,numRencontre);
          statementP6N.executeUpdate();
          PreparedStatement statementP7N = conn.prepareStatement(STMTP7N);
          statementP7N.setObject(1,i);
          statementP7N.setObject(2,numRencontre);
          statementP7N.executeUpdate();
          PreparedStatement statementP8N = conn.prepareStatement(STMTP8N);
          statementP8N.setObject(1,i);
          statementP8N.setObject(2,numRencontre);
          statementP8N.executeUpdate();

        }

        // Fermeture
        conn.commit();
        // rsetDrop.close();
        // rsetCreate.close();
        rset1.close();
        rset2.close();
        rset3.close();
        rset4.close();
        rset5.close();
        rset6.close();
        rset7.close();
        rset8.close();
        rset9.close();
        rset10.close();
        rset11.close();
        rset12.close();
        rset13.close();
        rset14.close();
        rset15.close();
        rset16.close();
        rset17.close();
        rset18.close();
        rset19.close();
        rset20.close();
        rset21.close();
        rset22.close();
        rset23.close();
        rset24.close();
        rset25.close();
        rset26.close();
        rset27.close();
        rset28.close();
        rset29.close();
        rset30.close();
        rset31.close();
        rset32.close();
        rset33.close();
        rset34.close();
        rset35.close();
        rset36.close();
        rset37.close();
        rset38.close();
        rset39.close();
        rset40.close();
        rset41.close();
        rset42.close();
        rset43.close();
        rset44.close();
        rset45.close();
        rset46.close();
        rset47.close();
        rset48.close();
        rset49.close();
        rset50.close();
        rset51.close();
        rset52.close();
        rset53.close();
        rset54.close();
        rset55.close();
        rset56.close();
        rset57.close();
        rset58.close();
        rset59.close();
        rset60.close();
        rset61.close();
        rset62.close();
        rset63.close();
        rset64.close();
        rset65.close();
        rset66.close();
        rset67.close();
        rset68.close();
        rset69.close();
        rset70.close();
        rset71.close();
        rset72.close();
        rset73.close();
        rset74.close();
        rset75.close();
        rset76.close();
        rset77.close();
        rset78.close();
        rset79.close();
        rset80.close();
        rset81.close();
        rset82.close();
        rset83.close();
        rset84.close();
        rset85.close();
        rset86.close();
        rset87.close();
        rset88.close();
        rset89.close();
        rset90.close();
        rset91.close();
        rset92.close();
        rset93.close();
        rset94.close();
        rset95.close();
        rset96.close();
        rset97.close();
        rset98.close();
        rset99.close();
        rset100.close();
        rset101.close();
        rset102.close();
        rset103.close();
        rset104.close();
        rset105.close();
        rset106.close();
        rset107.close();
        rset108.close();
        rset109.close();
        rset110.close();
        rset111.close();
        rset112.close();

        stmt.close();
        conn.close();

    } catch (SQLException e) {
        System.err.println("failed");
        e.printStackTrace(System.err);
      }
  }

  public static void main(String args[]) {
    new InitPion(10);
  }

}
